// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Playground.Api.Data;

#nullable disable

namespace Playground.Api.Migrations
{
    [DbContext(typeof(PlaygroundDbContext))]
    partial class PlaygroundDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Playground.Api.Models.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "We are excited to announce the release of Playground Platform v2.0, featuring enhanced performance and a redesigned interface.",
                            IsActive = true,
                            PublishedAt = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Platform v2.0 Launched",
                            Type = "success"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Infrastructure maintenance scheduled for Sunday April 5, 2026 from 02:00 to 04:00 UTC. Expect brief service interruptions.",
                            IsActive = true,
                            PublishedAt = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Scheduled Maintenance Window",
                            Type = "warning"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Three new AI-powered modules are now available in beta: Smart Search, Auto-Tagging, and Predictive Analytics.",
                            IsActive = true,
                            PublishedAt = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "New AI Features Available",
                            Type = "info"
                        });
                });

            modelBuilder.Entity("Playground.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Software",
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Real-time analytics and reporting platform with interactive charts and KPI tracking.",
                            ImageUrl = "https://picsum.photos/seed/prod1/400/300",
                            IsActive = true,
                            Name = "Analytics Dashboard",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Infrastructure",
                            CreatedAt = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Enterprise-grade cloud storage with 10TB capacity, versioning, and team collaboration.",
                            ImageUrl = "https://picsum.photos/seed/prod2/400/300",
                            IsActive = true,
                            Name = "Cloud Storage Pro",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = 3,
                            Category = "AI/ML",
                            CreatedAt = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Intelligent document extraction and classification powered by machine learning.",
                            ImageUrl = "https://picsum.photos/seed/prod3/400/300",
                            IsActive = true,
                            Name = "AI Document Processor",
                            Price = 499.99m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Productivity",
                            CreatedAt = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "All-in-one workspace for teams \u2014 chat, video, tasks, and file sharing.",
                            ImageUrl = "https://picsum.photos/seed/prod4/400/300",
                            IsActive = true,
                            Name = "Team Collaboration Suite",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Security",
                            CreatedAt = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Automated vulnerability scanning and compliance reporting for web applications.",
                            ImageUrl = "https://picsum.photos/seed/prod5/400/300",
                            IsActive = true,
                            Name = "Security Scanner",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 6,
                            Category = "DevOps",
                            CreatedAt = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "CI/CD automation platform with built-in container orchestration and deployment.",
                            ImageUrl = "https://picsum.photos/seed/prod6/400/300",
                            IsActive = false,
                            Name = "DevOps Pipeline",
                            Price = 349.99m
                        });
                });

            modelBuilder.Entity("Playground.Api.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "https://i.pravatar.cc/150?img=1",
                            Department = "Engineering",
                            Email = "sarah.johnson@playground.dev",
                            IsActive = true,
                            JoinedAt = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sarah Johnson",
                            Role = "Chief Technology Officer"
                        },
                        new
                        {
                            Id = 2,
                            AvatarUrl = "https://i.pravatar.cc/150?img=3",
                            Department = "Engineering",
                            Email = "marcus.williams@playground.dev",
                            IsActive = true,
                            JoinedAt = new DateTime(2022, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marcus Williams",
                            Role = "Lead Backend Developer"
                        },
                        new
                        {
                            Id = 3,
                            AvatarUrl = "https://i.pravatar.cc/150?img=5",
                            Department = "Design",
                            Email = "priya.patel@playground.dev",
                            IsActive = true,
                            JoinedAt = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Priya Patel",
                            Role = "UX/UI Designer"
                        },
                        new
                        {
                            Id = 4,
                            AvatarUrl = "https://i.pravatar.cc/150?img=7",
                            Department = "AI/ML",
                            Email = "david.chen@playground.dev",
                            IsActive = true,
                            JoinedAt = new DateTime(2023, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "David Chen",
                            Role = "Data Scientist"
                        },
                        new
                        {
                            Id = 5,
                            AvatarUrl = "https://i.pravatar.cc/150?img=9",
                            Department = "Product",
                            Email = "emily.rodriguez@playground.dev",
                            IsActive = true,
                            JoinedAt = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Emily Rodriguez",
                            Role = "Product Manager"
                        },
                        new
                        {
                            Id = 6,
                            AvatarUrl = "https://i.pravatar.cc/150?img=11",
                            Department = "Engineering",
                            Email = "james.thompson@playground.dev",
                            IsActive = true,
                            JoinedAt = new DateTime(2023, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "James Thompson",
                            Role = "DevOps Engineer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
